
from enum import Enum

class TokenType(Enum):
    EOF = "$"
    ERROR = "ERROR"

    ID = "ID"
    NUM = "NUMBER"
    STR = "STRING"

    # X86 Registers
    RAX = "rax"
    EAX = "eax"
    AX = "ax"
    AL = "al"
    RBX = "rbx"
    EBX = "ebx"
    BX = "bx"
    BL = "bl"
    RCX = "rcx"
    ECX = "ecx"
    CX = "cx"
    CL = "cl"
    RDX = "rdx"
    EDX = "edx"
    DX = "dx"
    DL = "dl"
    RSI = "rsi"
    ESI = "esi"
    SI = "si"
    SIL = "sil"
    RDI = "rdi"
    EDI = "edi"
    DI = "di"
    DIL = "dil"
    RBP = "rbp"
    EBP = "ebp"
    BP = "bp"
    BPL = "bpl"
    RSP = "rsp"
    ESP = "esp"
    SP = "sp"
    SPL = "spl"
    R8 = "r8"
    R8D = "r8d"
    R8W = "r8w"
    R8B = "r8b"
    R9 = "r9"
    R9D = "r9d"
    R9W = "r9w"
    R9B = "r9b"
    R10 = "r10"
    R10D = "r10d"
    R10W = "r10w"
    R10B = "r10b"
    R11 = "r11"
    R11D = "r11d"
    R11W = "r11w"
    R11B = "r11b"
    R12 = "r12"
    R12D = "r12d"
    R12W = "r12w"
    R12B = "r12b"
    R13 = "r13"
    R13D = "r13d"
    R13W = "r13w"
    R13B = "r13b"
    R14 = "r14"
    R14D = "r14d"
    R14W = "r14w"
    R14B = "r14b"
    R15 = "r15"
    R15D = "r15d"
    R15W = "r15w"
    R15B = "r15b"


    # X86 INSTRUCTIONS
    MOV = "mov"
    LEA = "lea"
    MOVZX = "movzx"
    CBW = "cbw"
    CWD = "cwd"
    CWDE = "cwde"
    CDQ = "cdq"
    CDQE = "cdqe"
    CQO = "cqo"
    MOVSX = "movsx"
    MOVSXD = "movsxd"
    ADD = "add"
    INC = "inc"
    ADC = "adc"
    SUB = "sub"
    DEC = "dec"
    MUL = "mul"
    IMUL = "imul"
    DIV = "div"
    IDIV = "idiv"
    AND = "and"
    OR = "or"
    XOR = "xor"
    NOT = "not"
    SHL = "shl"
    SHR = "shr"
    SAL = "sal"
    SAR = "sar"
    ROL = "rol"
    ROR = "ror"
    JMP = "jmp"
    CMP = "cmp"
    JE = "je"
    JNE = "jne"
    JL = "jl"
    JLE = "jle"
    JG = "jg"
    JGE = "jge"
    JB = "jb"
    JBE = "jbe"
    JA = "ja"
    JAE = "jae"
    LOOP = "loop"
    PUSH = "push"
    POP = "pop"
    CALL = "call"
    RET = "ret"
    MOVSS = "movss"
    MOVSD = "movsd"
    CVTSS2SD = "cvtss2sd"
    CVTSD2SS = "cvtsd2ss"
    CVTSS2SI = "cvtss2si"
    CVTSD2SI = "cvtsd2si"
    CVTSI2SS = "cvtss2si"
    CVTSI2SD = "cvtsi2sd"
    ADDSS = "addss"
    ADDSD = "addsd"
    SUBSS = "subss"
    SUBSD = "subsd"
    MULSS = "mulss"
    MULSD = "mulsd"
    DIVSS = "divss"
    DIVSD = "divsd"
    SQRTSS = "sqrtss"
    SQRTSD = "sqrtsd"
    UCOMISS = "ucomiss"
    UCOMISD = "ucomisd"


    # Additional x86 instruction Jonah told me to check for
    CMOVL = "cmovl"
    CMOVG = "cmovg"
    ASR = "asr"
    JNZ = "jnz"
    REL = "rel"
    DEFINE = "%define"


    # OPERATORS
    PLUS = "+"
    MINUS = "-"
    MULT = "*"
    DIV = "/"
    MOD = "%"
    BOR = "|"
    BAND = "&"


    # DELIMITERS
    PERIOD = "."
    COMMA = ","
    LPAREN = "("
    RPAREN = ")"
    LBRACK = "["
    RBRACK = "]"
    COLON = ":"
    PERCENT = "%"
    SQUOTE = "\'"
    DQUOTE = "\""
