
from enum import Enum

class TokenType(Enum):
    EOF = "$"
    ERROR = "ERROR"

    ID = "ID"
    NUM = "NUMBER"
    STR = "STRING"

    # X86 Registers
    RAX = "rax"
    EAX = "eax"
    AX = "ax"
    AL = "al"

    RBX = "rbx"
    EBX = "ebx"
    BX = "bx"
    BL = "bl"

    RCX = "rcx"
    ECX = "ecx"
    CX = "cx"
    CL = "cl"

    RDX = "rdx"
    EDX = "edx"
    DX = "dx"
    DL = "dl"

    RSI = "rsi"
    ESI = "esi"
    SI = "si"
    SIL = "sil"

    RDI = "rdi"
    EDI = "edi"
    DI = "di"
    DIL = "dil"

    RBP = "rbp"
    EBP = "ebp"
    BP = "bp"
    BPL = "bpl"

    RSP = "rsp"
    ESP = "esp"
    SP = "sp"
    SPL = "spl"

    R8 = "r8"
    R8D = "r8d"
    R8W = "r8w"
    R8B = "r8b"

    R9 = "r9"
    R9D = "r9d"
    R9W = "r9w"
    R9B = "r9b"

    R10 = "r10"
    R10D = "r10d"
    R10W = "r10w"
    R10B = "r10b"

    R11 = "r11"
    R11D = "r11d"
    R11W = "r11w"
    R11B = "r11b"

    R12 = "r12"
    R12D = "r12d"
    R12W = "r12w"
    R12B = "r12b"

    R13 = "r13"
    R13D = "r13d"
    R13W = "r13w"
    R13B = "r13b"

    R14 = "r14"
    R14D = "r14d"
    R14W = "r14w"
    R14B = "r14b"

    R15 = "r15"
    R15D = "r15d"
    R15W = "r15w"
    R15B = "r15b"

    XMM0 = "xmm0"
    XMM1 = "xmm1"
    XMM2 = "xmm2"
    XMM3 = "xmm3"
    XMM4 = "xmm4"
    XMM5 = "xmm5"
    XMM6 = "xmm6"
    XMM7 = "xmm7"
    XMM8 = "xmm8"
    XMM9 = "xmm9"
    XMM10 = "xmm10"
    XMM11 = "xmm11"
    XMM12 = "xmm12"
    XMM13 = "xmm13"
    XMM14 = "xmm14"
    XMM15 = "xmm15"

    # X86 Data Types
    EQU = "equ"
    DB = "db"
    DW = "dw"
    DD = "dd"
    DQ = "dq"
    DDQ = "ddq"
    DT = "dt"
    RESB = "resb"
    RESW = "resw"
    RESD = "resd"
    RESQ = "resq"
    RESDQ = "resdq"
    BYTE = "byte"
    WORD = "word"
    DWORD = "dword"
    QWORD = "qword"
    SECTION = "section"
    GLOBAL = "global"

    # X86 INSTRUCTIONS
    MOV = "mov"
    LEA = "lea"
    MOVZX = "movzx"
    CBW = "cbw"
    CWD = "cwd"
    CWDE = "cwde"
    CDQ = "cdq"
    CDQE = "cdqe"
    CQO = "cqo"
    MOVSX = "movsx"
    MOVSXD = "movsxd"
    ADD = "add"
    INC = "inc"
    ADC = "adc"
    SUB = "sub"
    DEC = "dec"
    MUL = "mul"
    IMUL = "imul"
    DIV = "div"
    IDIV = "idiv"
    AND = "and"
    OR = "or"
    XOR = "xor"
    NOT = "not"
    SHL = "shl"
    SHR = "shr"
    SAL = "sal"
    SAR = "sar"
    ROL = "rol"
    ROR = "ror"
    JMP = "jmp"
    CMP = "cmp"
    JE = "je"
    JNE = "jne"
    JL = "jl"
    JLE = "jle"
    JG = "jg"
    JGE = "jge"
    JB = "jb"
    JBE = "jbe"
    JA = "ja"
    JAE = "jae"
    LOOP = "loop"
    PUSH = "push"
    POP = "pop"
    CALL = "call"
    RET = "ret"
    MOVSS = "movss"
    MOVSD = "movsd"
    CVTSS2SD = "cvtss2sd"
    CVTSD2SS = "cvtsd2ss"
    CVTSS2SI = "cvtss2si"
    CVTSD2SI = "cvtsd2si"
    CVTSI2SS = "cvtsi2ss"
    CVTSI2SD = "cvtsi2sd"
    ADDSS = "addss"
    ADDSD = "addsd"
    SUBSS = "subss"
    SUBSD = "subsd"
    MULSS = "mulss"
    MULSD = "mulsd"
    DIVSS = "divss"
    DIVSD = "divsd"
    SQRTSS = "sqrtss"
    SQRTSD = "sqrtsd"
    UCOMISS = "ucomiss"
    UCOMISD = "ucomisd"
    SYSCALL = "syscall"


    # Additional x86 instruction Jonah told me to check for
    CMOVL = "cmovl"
    CMOVG = "cmovg"
    ASR = "asr"
    JNZ = "jnz"
    REL = "rel"
    DEFINE = "%define"



    # MIPS Instructions
    ABS = "abs"
    ADDU = "addu"
    DIVU = "divu"
    MULO = "mulo"
    MULOU = "mulou"
    MULT = "mult"
    MULTU = "multu"
    NEG = "neg"
    REM = "rem"
    REMU = "remu"
    SUBU = "subu"
    SEQ = "seq"
    SGE = "sge"
    SGEU = "sgeu"
    SGT = "sgt"
    SGTU = "sgtu"
    SLE = "sle"
    SLEU = "sleu"
    SLT = "slt"
    SLTI = "slti"
    SLTU = "sltu"
    SLTIU = "sltiu"
    SNE = "sne"
    BRANCH = "b"
    BCZT = "bczt"
    BCZF = "bczf"
    BEQ = "beq"
    BEQZ = "beqz"
    BGE = "bge"
    BGEU = "bgeu"
    BGEZ = "bgez"
    BGEZAL = "bgezal"
    BGT = "bgt"
    BGTU = "bgtu"
    BGTZ = "bgtz"
    BLE = "ble"
    BLEU = "bleu"
    BLEZ = "blez"
    BLEZAL = "blezal"
    BLTZAL = "bltzal"
    BLT = "blt"
    BLTU = "bltu"
    BLTZ = "bltz"
    BNE = "bne"
    BNEZ = "bnez"
    JUMP = "j"
    JAL = "jal"
    JALR = "jalr"
    JR = "jr"
    LA = "la"
    LB = "lb"
    LBU = "lbu"
    LD = "ld"
    LH = "lh"
    LHU = "lhu"
    LW = "lw"
    LWCZ = "lwcz"
    LWL = "lwl"
    LWR = "lwr"
    ULH = "ulh"
    ULHU = "ulhu"
    ULW = "ulw"
    LI = "li"
    LUI = "lui"
    ANDI = "andi"
    NOR = "nor"
    ORI = "ori"
    SLL = "sll"
    SRA = "SRA"
    SRL = "srl"
    XORI = "xori"
    SB = "sb"
    SD = "sd"
    SH = "sh"
    SW = "sw"
    SWCZ = "swcz"
    SWL = "swl"
    SWR = "swr"
    USH = "ush"
    USW = "usw"
    MOVE = "move"
    MFHI = "mfhi"
    MFLO = "mflo"
    MTHI = "mthi"
    MTLO = "mtlo"
    MFC1 = "mfc1"
    MFC1D = "mfc1.d"
    MTC1 = "mtc1"
    MTC1D = "mtc1.d"
    ABSD = "abs.d"
    ABSS = "abs.s"
    ADDD = "add.d"
    ADDS = "add.s"
    CEQD = "c.eq.d"
    CEQS = "c.eq.s"
    CLED = "c.le.d"
    CLES = "c.le.s"
    CLTD = "c.lt.d"
    CLTS = "c.lt.s"
    CVTDS = "cvt.d.s"
    CVTDW = "cvt.d.w"
    CVTSD = "cvt.s.d"
    CVTSW = "cvt.s.w"
    CVTWD = "cvt.w.d"
    CVTWS = "cvt.w.s"
    DIVD = "div.d"
    DIVS = "div.s"
    LDD = "l.d"
    LDS = "l.s"
    MOVD = "mov.d"
    MOVS = "mov.s"
    MULD = "mul.d"
    MULS = "mul.s"
    NEGD = "neg.d"
    NEGS = "neg.s"
    SDD = "s.d"
    SDS = "s.s"
    SUBD = "sub.d"
    SUBS = "sub.s"
    RFE = "rfe"
    BREAK = "break"
    NOP = "nop"


    # OPERATORS
    PLUS = "+"
    MINUS = "-"
    MULTIPLY = "*"
    DIVIDE = "/"
    MOD = "%"
    BOR = "|"
    BAND = "&"


    # DELIMITERS
    PERIOD = "."
    COMMA = ","
    LPAREN = "("
    RPAREN = ")"
    LBRACK = "["
    RBRACK = "]"
    COLON = ":"
    PERCENT = "%"
    SQUOTE = "\'"
    DQUOTE = "\""
    DOLLAR = "$"
