# Generated by Django 5.1.5 on 2025-04-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CheatingGroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cluster_distance", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="CheatingGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cohesion_score", models.FloatField()),
                ("analysis_report_path", models.TextField(unique=True)),
            ],
            options={
                "db_table_comment": "Recorded cheating groups for a given assignment.",
            },
        ),
        migrations.CreateModel(
            name="ConfirmedCheaters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("confirmed_date", models.DateField()),
                ("threshold_used", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="FlaggedStudents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("generative_ai", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="LongitudinalCheatingGroupInstances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LongitudinalCheatingGroupMembers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_core_member", models.BooleanField()),
                ("appearance_count", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LongitudinalCheatingGroups",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionSimiliarityPairs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=50)),
                ("match_id", models.BigIntegerField()),
                ("percentage", models.IntegerField()),
            ],
        ),
    ]
