# Generated by Django 5.1.5 on 2025-04-20 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        ("cheating", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="cheatinggroups",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="cheatinggroupmembers",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="confirmedcheaters",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="confirmedcheaters",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupinstances",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupmembers",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupinstances",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student_reports",
                to="cheating.assignmentreport",
            ),
        ),
        migrations.AddField(
            model_name="studentreport",
            name="submission",
            field=models.ForeignKey(
                help_text="The student submission referenced",
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="course_catalog",
            field=models.ForeignKey(
                help_text="The course this profile belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursecatalog",
            ),
        ),
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="semester",
            field=models.ForeignKey(
                help_text="The semester this profile covers",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.semester",
            ),
        ),
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="student",
            field=models.ForeignKey(
                help_text="Which student these features belong to",
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.students",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimilaritypairs",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimilaritypairs",
            name="submission_id_1",
            field=models.ForeignKey(
                db_column="submission_id_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimilaritypairs",
            name="submission_id_2",
            field=models.ForeignKey(
                db_column="submission_id_2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissionsimilaritypairs_submission_id_2_set",
                to="assignments.submissions",
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="similarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.submissionsimilaritypairs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="confirmedcheaters",
            unique_together={("student", "assignment")},
        ),
        migrations.AddIndex(
            model_name="studentreport",
            index=models.Index(
                fields=["submission"], name="cheating_st_submiss_8c4884_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentreport",
            index=models.Index(
                fields=["z_score"], name="cheating_st_z_score_8757a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentreport",
            index=models.Index(
                fields=["mean_similarity"], name="cheating_st_mean_si_708c80_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentreport",
            unique_together={("report", "submission")},
        ),
        migrations.AlterUniqueTogether(
            name="studentsemesterprofile",
            unique_together={("student", "course_catalog", "semester")},
        ),
        migrations.AlterUniqueTogether(
            name="submissionsimilaritypairs",
            unique_together={("submission_id_1", "submission_id_2", "assignment")},
        ),
        migrations.AlterUniqueTogether(
            name="flaggedstudents",
            unique_together={("student", "similarity")},
        ),
    ]
