# Generated by Django 5.1.5 on 2025-04-16 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0002_initial"),
        ("cheating", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="cheatinggroups",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="cheatinggroupmembers",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="confirmedcheaters",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="confirmedcheaters",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupinstances",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupmembers",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="longitudinalcheatinggroupinstances",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimiliaritypairs",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimiliaritypairs",
            name="submission_id_1",
            field=models.ForeignKey(
                db_column="submission_id_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AddField(
            model_name="submissionsimiliaritypairs",
            name="submission_id_2",
            field=models.ForeignKey(
                db_column="submission_id_2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissionsimiliaritypairs_submission_id_2_set",
                to="assignments.submissions",
            ),
        ),
        migrations.AddField(
            model_name="flaggedstudents",
            name="similarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.submissionsimiliaritypairs",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="confirmedcheaters",
            unique_together={("student", "assignment")},
        ),
        migrations.AlterUniqueTogether(
            name="submissionsimiliaritypairs",
            unique_together={("submission_id_1", "submission_id_2")},
        ),
        migrations.AlterUniqueTogether(
            name="flaggedstudents",
            unique_together={("student", "similarity")},
        ),
    ]
