# Generated by Django 5.1.5 on 2025-04-22 01:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="avg_z_score_squared",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="max_z_score_cubed",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="studentsemesterprofile",
            name="feature_vector",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                help_text="Full feature vector for clustering",
                size=10,
            ),
        ),
    ]
