# Generated by Django 5.1.5 on 2025-04-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignments_course_instance_and_more"),
        ("cheating", "0002_initial"),
        ("courses", "0003_alter_courseassignmentcollaboration_assignment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatinggroupmembers",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AlterField(
            model_name="cheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AlterField(
            model_name="cheatinggroups",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="confirmedcheaters",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="confirmedcheaters",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AlterField(
            model_name="flaggedstudents",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AlterField(
            model_name="flaggedstudents",
            name="similarity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.submissionsimiliaritypairs",
            ),
        ),
        migrations.AlterField(
            model_name="flaggedstudents",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AlterField(
            model_name="longitudinalcheatinggroupinstances",
            name="cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.cheatinggroups",
            ),
        ),
        migrations.AlterField(
            model_name="longitudinalcheatinggroupinstances",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AlterField(
            model_name="longitudinalcheatinggroupmembers",
            name="longitudinal_cheating_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="cheating.longitudinalcheatinggroups",
            ),
        ),
        migrations.AlterField(
            model_name="longitudinalcheatinggroupmembers",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AlterField(
            model_name="submissionsimiliaritypairs",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="submissionsimiliaritypairs",
            name="submission_id_1",
            field=models.ForeignKey(
                db_column="submission_id_1",
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AlterField(
            model_name="submissionsimiliaritypairs",
            name="submission_id_2",
            field=models.ForeignKey(
                db_column="submission_id_2",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="submissionsimiliaritypairs_submission_id_2_set",
                to="assignments.submissions",
            ),
        ),
    ]
