# Generated by Django 5.1.5 on 2025-04-19 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0004_remove_assignments_lock_date_after_due_date_and_more"),
        ("cheating", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "mu",
                    models.FloatField(
                        help_text="Population mean of all similarity scores"
                    ),
                ),
                ("sigma", models.FloatField(help_text="Population standard deviation")),
                (
                    "variance",
                    models.FloatField(help_text="Population variance (sigma^2)"),
                ),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="assignments.assignments",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mean_similarity",
                    models.FloatField(help_text="Student’s sample mean similarity"),
                ),
                (
                    "z_score",
                    models.FloatField(
                        help_text="The student’s z-score of mean similarity"
                    ),
                ),
                (
                    "ci_lower",
                    models.FloatField(
                        help_text="Lower bound of 95% CI for mean similarity"
                    ),
                ),
                (
                    "ci_upper",
                    models.FloatField(
                        help_text="Upper bound of 95% CI for mean similarity"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_reports",
                        to="cheating.assignmentreport",
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        help_text="The student submission referenced",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="assignments.submissions",
                    ),
                ),
            ],
            options={
                "ordering": ["-z_score"],
                "unique_together": {("report", "submission")},
            },
        ),
    ]
