# Generated by Django 5.1.5 on 2025-04-22 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0003_studentsemesterprofile_avg_z_score_squared_and_more"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PairFlagStat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assignments_shared", models.PositiveIntegerField(default=0)),
                ("flagged_count", models.PositiveIntegerField(default=0)),
                ("total_similarity", models.FloatField(default=0.0)),
                ("total_z_score", models.FloatField(default=0.0)),
                (
                    "course_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursecatalog",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
                (
                    "student_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
                (
                    "student_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("course_catalog", "semester", "student_a", "student_b")
                },
            },
        ),
    ]
