# Generated by Django 5.1.5 on 2025-04-22 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0004_pairflagstat"),
    ]

    operations = [
        migrations.AddField(
            model_name="pairflagstat",
            name="kmeans_label",
            field=models.SmallIntegerField(
                blank=True, help_text="Cluster ID from latest KMeans run", null=True
            ),
        ),
        migrations.AddField(
            model_name="pairflagstat",
            name="max_z_score",
            field=models.FloatField(default=0.0),
        ),
    ]
