# Generated by Django 5.1.5 on 2025-04-22 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0005_pairflagstat_kmeans_label_pairflagstat_max_z_score"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentsemesterprofile",
            old_name="cluster_label",
            new_name="kmeans_label",
        ),
    ]
