# Generated by Django 5.1.5 on 2025-04-22 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0006_rename_cluster_label_studentsemesterprofile_kmeans_label"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentsemesterprofile",
            old_name="kmeans_label",
            new_name="cluster_label",
        ),
    ]
