# Generated by Django 5.1.5 on 2025-04-22 22:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0007_rename_kmeans_label_studentsemesterprofile_cluster_label"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentsemesterprofile",
            name="submissions_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Total submissions this student made in that semester",
            ),
        ),
        migrations.AlterField(
            model_name="studentsemesterprofile",
            name="feature_vector",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                help_text="Full feature vector for clustering",
                size=11,
            ),
        ),
    ]
