# Generated by Django 5.1.5 on 2025-04-22 23:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0008_studentsemesterprofile_submissions_count_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentsemesterprofile",
            name="assignments_flagged",
        ),
        migrations.RemoveField(
            model_name="studentsemesterprofile",
            name="avg_z_score_squared",
        ),
        migrations.RemoveField(
            model_name="studentsemesterprofile",
            name="max_z_score_cubed",
        ),
        migrations.RemoveField(
            model_name="studentsemesterprofile",
            name="submissions_count",
        ),
        migrations.AlterField(
            model_name="studentsemesterprofile",
            name="feature_vector",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.FloatField(),
                help_text="[avg_z, max_z, num_flagged, sim_var, sim_skew, sim_kurt, high_frac]",
                size=7,
            ),
        ),
        migrations.AlterField(
            model_name="studentsemesterprofile",
            name="high_similarity_fraction",
            field=models.FloatField(
                help_text="Fraction of *all* pairwise comparisons > threshold across the semester"
            ),
        ),
        migrations.AlterField(
            model_name="studentsemesterprofile",
            name="num_flagged_assignments",
            field=models.PositiveIntegerField(
                help_text="How many assignments where z > threshold"
            ),
        ),
    ]
