# Generated by Django 5.1.5 on 2025-04-23 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cheating", "0009_remove_studentsemesterprofile_assignments_flagged_and_more"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlaggedStudentPair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mean_similarity", models.FloatField()),
                ("max_similarity", models.FloatField()),
                ("mean_z_score", models.FloatField()),
                ("max_z_score", models.FloatField()),
                ("flagged_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course_catalog",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.coursecatalog",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="courses.semester",
                    ),
                ),
                (
                    "student_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
                (
                    "student_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="courses.students",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("course_catalog", "semester", "student_a", "student_b")
                },
            },
        ),
    ]
