# Generated by Django 5.1.5 on 2025-04-17 01:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("courses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="professors",
            name="user",
            field=models.OneToOneField(
                help_text="User associated with the professor.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="professorenrollments",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AddField(
            model_name="courseinstances",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="semester",
            unique_together={("year", "term", "session")},
        ),
        migrations.AddField(
            model_name="courseinstances",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.semester"
            ),
        ),
        migrations.AddField(
            model_name="studentenrollments",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AddField(
            model_name="studentenrollments",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="teachingassistantenrollments",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AddField(
            model_name="teachingassistants",
            name="user",
            field=models.OneToOneField(
                help_text="User associated with the teaching assistant.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="teachingassistantenrollments",
            name="teaching_assistant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teachingassistants",
            ),
        ),
        migrations.AddField(
            model_name="courseinstances",
            name="teaching_assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teachingassistants",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="professorenrollments",
            unique_together={("professor", "course_instance")},
        ),
        migrations.AlterUniqueTogether(
            name="studentenrollments",
            unique_together={("student", "course_instance")},
        ),
        migrations.AlterUniqueTogether(
            name="teachingassistantenrollments",
            unique_together={("teaching_assistant", "course_instance")},
        ),
        migrations.AlterUniqueTogether(
            name="courseinstances",
            unique_together={
                ("semester", "course_catalog", "section_number", "professor")
            },
        ),
    ]
