# Generated by Django 5.1.5 on 2025-04-03 04:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_alter_assignments_course_instance_and_more"),
        ("courses", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseassignmentcollaboration",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="courseassignmentcollaboration",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="courseinstances",
            name="course_catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.coursecatalog"
            ),
        ),
        migrations.AlterField(
            model_name="courseinstances",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AlterField(
            model_name="courseinstances",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.coursessemester",
            ),
        ),
        migrations.AlterField(
            model_name="courseinstances",
            name="teaching_assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teachingassistants",
            ),
        ),
        migrations.AlterField(
            model_name="professorenrollments",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="professorenrollments",
            name="professor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.professors"
            ),
        ),
        migrations.AlterField(
            model_name="professors",
            name="user",
            field=models.OneToOneField(
                help_text="User associated with the professor.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollments",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="studentenrollments",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AlterField(
            model_name="teachingassistantenrollment",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="teachingassistantenrollment",
            name="teaching_assistant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.teachingassistants",
            ),
        ),
        migrations.AlterField(
            model_name="teachingassistants",
            name="user",
            field=models.OneToOneField(
                help_text="User associated with the teaching assistant.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
