# Generated by Django 5.1.5 on 2025-04-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeachingAssistantEnrollment",
            new_name="TeachingAssistantEnrollments",
        ),
    ]
