# Generated by Django 5.1.5 on 2025-04-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_courseassignmentcollaboration_assignment_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CoursesSemester",
            new_name="Semester",
        ),
    ]
