# Generated by Django 5.1.5 on 2025-05-02 06:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basefiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="base_files",
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="constraints",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="constraints",
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="requiredsubmissionfiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="required_files",
                to="assignments.assignments",
            ),
        ),
    ]
