# Generated by Django 5.1.5 on 2025-04-17 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assignments", "0001_initial"),
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="course_catalog",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.coursecatalog"
            ),
        ),
        migrations.AddField(
            model_name="assignments",
            name="semester",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.semester"
            ),
        ),
        migrations.AddField(
            model_name="basefiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="bulksubmissions",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="bulksubmissions",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AddField(
            model_name="constraints",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="policyviolations",
            name="constraint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.constraints",
            ),
        ),
        migrations.AddField(
            model_name="requiredsubmissionfiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="submissions",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AddField(
            model_name="submissions",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AddField(
            model_name="submissions",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
        migrations.AddField(
            model_name="policyviolations",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="assignments",
            unique_together={("course_catalog", "semester", "assignment_number")},
        ),
        migrations.AlterUniqueTogether(
            name="basefiles",
            unique_together={("assignment", "file_name")},
        ),
        migrations.AlterUniqueTogether(
            name="bulksubmissions",
            unique_together={("course_instance", "assignment")},
        ),
        migrations.AlterUniqueTogether(
            name="requiredsubmissionfiles",
            unique_together={("assignment", "file_name")},
        ),
        migrations.AlterUniqueTogether(
            name="submissions",
            unique_together={("assignment", "student")},
        ),
        migrations.AlterUniqueTogether(
            name="policyviolations",
            unique_together={("submission", "constraint", "line_number")},
        ),
    ]
