# Generated by Django 5.1.5 on 2025-02-24 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.class'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.professor'),
        ),
        migrations.AddField(
            model_name='flaggedsubmission',
            name='similarity_with',
            field=models.ManyToManyField(related_name='similar_submissions', to='assignments.student'),
        ),
        migrations.AddField(
            model_name='flaggedstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.student'),
        ),
        migrations.AddField(
            model_name='confirmedcheater',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.student'),
        ),
        migrations.AddField(
            model_name='submission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.assignment'),
        ),
        migrations.AddField(
            model_name='submission',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.professor'),
        ),
        migrations.AddField(
            model_name='submission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.student'),
        ),
        migrations.AddField(
            model_name='flaggedsubmission',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignments.submission'),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('class_instance', 'assignment_number')},
        ),
    ]
