# Generated by Django 5.1.5 on 2025-04-03 04:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignments",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="basefiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="bulksubmissions",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="bulksubmissions",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="constraints",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="policyviolations",
            name="constraint",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.constraints",
            ),
        ),
        migrations.AlterField(
            model_name="policyviolations",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.submissions",
            ),
        ),
        migrations.AlterField(
            model_name="requiredsubmissionfiles",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="submissions",
            name="assignment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="assignments.assignments",
            ),
        ),
        migrations.AlterField(
            model_name="submissions",
            name="course_instance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.courseinstances",
            ),
        ),
        migrations.AlterField(
            model_name="submissions",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.students"
            ),
        ),
    ]
