# Generated by Django 5.1.5 on 2025-04-18 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0002_initial"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignments",
            name="lock_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Date & time when submissions are locked.",
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="assignments",
            constraint=models.CheckConstraint(
                condition=models.Q(("lock_date__gte", models.F("due_date"))),
                name="lock_date_after_due_date",
            ),
        ),
    ]
