# Generated by Django 5.1.5 on 2025-04-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0003_assignments_lock_date_and_more"),
        ("courses", "0002_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="assignments",
            name="lock_date_after_due_date",
        ),
        migrations.AddConstraint(
            model_name="assignments",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("lock_date__isnull", True),
                    ("lock_date__gte", models.F("due_date")),
                    _connector="OR",
                ),
                name="lock_date_after_due_or_null",
            ),
        ),
    ]
